{{- if .Values.nextcloud.webcron.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-webcron
  {{- if .Values.nextcloud.commonAnnotations }}
  annotations: {{- dict "value" .Values.nextcloud.commonAnnotations "context" $ | nindent 4 }}
  {{- end }}
spec:
  schedule: "*/5 * * * *"
  startingDeadlineSeconds: 240
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-webcron
            image: busybox
            args:
            - /bin/sh
            - -c
            - |
              wget --spider --header 'Host: {{ .Values.nextcloud.domain }}' http://{{ .Release.Name }}/cron.php
          restartPolicy: OnFailure
{{- end }}