apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  {{- if .Values.nextcloud.commonAnnotations }}
  annotations: {{- dict "value" .Values.nextcloud.commonAnnotations "context" $ | nindent 4 }}
  {{- end }}
  labels:
    {{- include "nextcloud.redis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nextcloud.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.redis.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nextcloud.redis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.redis.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Release.Name }}-redis
          securityContext:
            {{- toYaml .Values.redis.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "nextcloud.secretName" . }}
                  key: REDIS_PASSWORD
          args:
            - --requirepass $(REDIS_PASSWORD)
          ports:
          - name: redis
            containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: {{ .Release.Name }}-redis
          {{- with .Values.redis.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      volumes:
        - name: {{ .Release.Name }}-redis
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-redis
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
