{{- if and (include "nextcloud.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nextcloud.secretName" . }}
  {{- if .Values.nextcloud.commonAnnotations }}
  annotations: {{- dict "value" .Values.nextcloud.commonAnnotations "context" $ | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  NC_ADMIN_USERNAME: {{ .Values.nextcloud.adminUsername | b64enc | quote }}
  NC_ADMIN_PASSWORD: {{ .Values.nextcloud.adminPassword | b64enc | quote }}
  NC_EMAIL_PASSWORD: {{ .Values.nextcloud.mail.auth.password | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc | quote }}
  {{- if eq .Values.nextcloud.databaseType "pgsql" }}
  POSTGRES_USER: {{ .Values.postgres.username | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.postgresPassword | b64enc | quote }}
  {{- end }}
{{- end }}
