{{- if (include "nextcloud.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nextcloud.secretName" . }}
  {{- if .Values.nextcloud.commonAnnotations }}
  annotations: {{- dict "value" .Values.nextcloud.commonAnnotations "context" $ | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.username | default "nextcloud" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.postgresPassword | default (randAlphaNum 32) | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | default "nextcloud" | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | default (randAlphaNum 128) | b64enc | quote }}
  NC_ADMIN_USERNAME: {{ .Values.adminUsername | default "ncadmin" | b64enc | quote }}
  NC_ADMIN_PASSWORD: {{ .Values.adminPassword | default (randAlphaNum 16) | b64enc | quote }}
{{- end -}}