apiVersion: v2
name: n8n
description: A N8N Helm chart for Kubernetes. n8n is a free and open fair-code licensed node-based Workflow Automation Tool.
type: application
version: 0.137.2
appVersion: "0.137.2"

keywords:
- n8n
- workflow
- automation
sources:
  - https://n8n.io/
  - https://github.com/n8n-io/n8n
  - https://github.com/DreemiX/helm-charts-n8n/tree/master/charts/n8n
home: https://github.com/DreemiX/helm-charts-n8n/tree/master/charts/n8n
icon: https://avatars.githubusercontent.com/u/45487711?s=200&v=4

dependencies:
  - name: postgresql
    version: 16.0.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mysql
    version: 11.1.19
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: mariadb
    version: 11.4.3
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: redis
    version: 20.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
